summary: Retrieve Deployment Configuration
description: Retrieve a deployment configuration by provider name.
operationId: getDeployment
parameters:
- name: provider
  in: path
  description: The deployment provider name (e.g. `vercel`, `netlify`).
  required: true
  schema:
    type: string
    enum:
      - vercel
      - netlify
- $ref: ../../../components/parameters.yaml#/Fields
- $ref: ../../../components/parameters.yaml#/Meta
responses:
  '200':
    description: Successful request
    content:
      application/json:
        schema:
          type: object
          properties:
            data:
              $ref: ../../../components/schemas/deployments.yaml
  '401':
    $ref: ../../../components/responses.yaml#/UnauthorizedError
  '404':
    $ref: ../../../components/responses.yaml#/NotFoundError
security: []
tags:
- Deployments
x-codeSamples:
- label: Directus SDK
  lang: JavaScript
  source: |
    import { createDirectus, rest, readDeployment } from '@directus/sdk';

    const client = createDirectus('directus_project_url').with(rest());

    const result = await client.request(readDeployment('vercel'));
- label: GraphQL
  lang: GraphQL
  source: |
    // Not supported in GraphQL
