# Based on https://github.com/directus/eslint-config/blob/main/.github/workflows/release.yml
# Version must already be bumped in package.json via a PR before running this workflow

name: Release

on:
  workflow_dispatch: {}

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.release }}
      is-prerelease: ${{ steps.version.outputs.prerelease && true || false }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/setup

      - name: Read version from package.json
        id: pkg-version
        run: echo "version=$(node -p 'require("./package.json").version')" >> "$GITHUB_OUTPUT"

      - name: Check version
        uses: madhead/semver-utils@v4
        id: version
        with:
          version: ${{ steps.pkg-version.outputs.version }}
          lenient: false

      - name: Build
        run: pnpm run build

  create-tag:
    name: Create Tag
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          version='v${{ needs.validate.outputs.version }}'

          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

          git tag --annotate "$version" --message "$version"

          git push origin "refs/tags/${version}"

  create-release:
    name: Create Release
    needs:
      - validate
      - create-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            'v${{ needs.validate.outputs.version }}' \
            --verify-tag \
            --generate-notes \
            ${{ needs.validate.outputs.is-prerelease == 'true' && '--prerelease' || '' }}

  publish-npm:
    name: Publish to NPM
    needs:
      - validate
      - create-tag
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: refs/tags/v${{ needs.validate.outputs.version }}

      - name: Setup env
        uses: ./.github/actions/setup
        with:
          registry: https://registry.npmjs.org

      - name: Build
        run: pnpm run build

      - name: Publish
        env:
          NPM_CONFIG_PROVENANCE: true
        run: |
          pnpm publish \
            --access=public \
            --no-git-checks \
            --tag ${{ needs.validate.outputs.is-prerelease == 'true' && 'canary' || 'latest' }}
